ALTER TABLE stores
ADD COLUMN IF NOT EXISTS store_lat NUMERIC(10, 8) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS store_lng NUMERIC(11, 8) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS max_delivery_radius NUMERIC DEFAULT 0;
