// <auto-generated />
using System;
using KioslyDesktop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KioslyDesktop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("KioslyDesktop.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT")
                        .HasColumnName("code");

                    b.Property<double>("CostPrice")
                        .HasColumnType("REAL")
                        .HasColumnName("cost_price");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT")
                        .HasColumnName("image_path");

                    b.Property<int>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted");

                    b.Property<int>("IsOnline")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_online");

                    b.Property<int>("IsSynced")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_synced");

                    b.Property<int>("MinStock")
                        .HasColumnType("INTEGER")
                        .HasColumnName("min_stock");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<double>("Price")
                        .HasColumnType("REAL")
                        .HasColumnName("price");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER")
                        .HasColumnName("stock");

                    b.Property<int>("Weight")
                        .HasColumnType("INTEGER")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.ToTable("products");
                });

            modelBuilder.Entity("KioslyDesktop.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CashierName")
                        .HasColumnType("TEXT")
                        .HasColumnName("cashier_name");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("customer_id");

                    b.Property<int>("IsSynced")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_synced");

                    b.Property<double>("PaidAmount")
                        .HasColumnType("REAL")
                        .HasColumnName("paid_amount");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("TEXT")
                        .HasColumnName("payment_method");

                    b.Property<double>("ServiceChargeAmount")
                        .HasColumnType("REAL")
                        .HasColumnName("service_charge_amount");

                    b.Property<int?>("ShiftId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("shift_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<double>("TaxAmount")
                        .HasColumnType("REAL")
                        .HasColumnName("tax_amount");

                    b.Property<double?>("TaxPercentage")
                        .HasColumnType("REAL")
                        .HasColumnName("tax_percentage");

                    b.Property<double>("TotalAmount")
                        .HasColumnType("REAL")
                        .HasColumnName("total_amount");

                    b.HasKey("Id");

                    b.ToTable("transactions");
                });

            modelBuilder.Entity("KioslyDesktop.Models.TransactionItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<double>("CostAtSale")
                        .HasColumnType("REAL")
                        .HasColumnName("cost_at_sale");

                    b.Property<int>("IsSynced")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_synced");

                    b.Property<double>("PriceAtSale")
                        .HasColumnType("REAL")
                        .HasColumnName("price_at_sale");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantity");

                    b.Property<int>("ReturnedQty")
                        .HasColumnType("INTEGER")
                        .HasColumnName("returned_qty");

                    b.Property<int>("TransactionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("transaction_id");

                    b.HasKey("Id");

                    b.ToTable("transaction_items");
                });
#pragma warning restore 612, 618
        }
    }
}
